apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespaces.faasFunc.name }}
  annotations:
    {{- if .Values.namespaces.faasFunc.linkerdInject.enabled }}
    linkerd.io/inject: enabled
    {{- end }}
    config.linkerd.io/skip-inbound-ports:  {{ .Values.namespaces.faasFunc.inPort | quote }}
    config.linkerd.io/skip-outbound-ports: {{ .Values.namespaces.faasFunc.outPort | quote  }}
  labels:
    role:  {{ .Values.namespaces.faasFunc.role }}