# Default values for openbackend-functions.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespaces:
  function: openbackend-fn

images:
  letter: mugiwaralabs/letterfaas:latest
